### ISSUE TITLE
Multiline equations (With ^)

### ISSUE THREAD

**Issue by DanielMReed** [ethereum/yellowpaper#655] opened 2018-03-03 08:42 UTC
Some equations use multiple lines to describe a single function/statement

Examples of correct (in this sense) use are : 
(16) (31) (37) (68) (148)

However equations that fail are:
(47-49)
(52 - 60)

**Comment by jamesray1** [comment] 2018-03-03 11:12
47-49 and 52-60  needs fixing, I agree.

**Comment by jamesray1** [comment] 2018-03-03 11:21
The problem is that equation 16 uses `\begin{equation}` while equations 47-49 and 52-60 use `\begin{eqnarray}`, which has the advantage of neatly aligning the equal sign or relational operator. It is not as easy to do this with `\begin{equation}`.

**Comment by jamesray1** [comment] 2018-03-03 11:22
I will try to use `\nonumber` on lines that we don't want an equation number for.

**Comment by jamesray1** [comment] 2018-03-03 11:27
I have confirmed that that will work, and will make a PR.

**Comment by jamesray1** [comment] 2018-03-03 11:31
#658. @pirapira, you can close this issue.

**Closed** 2018-03-06 15:08 UTC
